### ISSUE TITLE
Inverted Torcherino

### ISSUE THREAD

**Issue by sci4me** [sci4me/Torcherino#10]
yes...

**Comment by psychofad** [comment]
but what does this do?

**Comment by sci4me** [comment]
lol, I really though this was self explanatory...

the normal torcherino will be disabled by a redstone signal. the inverted one is enabled by a redstone signal, disabled without one.

:P not trying to call you dumb or anything, LOTS of people are confused by this for some reason...

**Comment by psychofad** [comment]
Lol...I just may be dumb..I had no idea you could disable it with a redstone signal in the first place. :P


-------- Original message --------

**Comment by sci4me** [comment]
You're not. TONS of ppl had this exact problem... :P
