### ISSUE TITLE
Not Affecting all Blocks

### ISSUE THREAD

**Issue by nalkrien** [sci4me/Torcherino#17]
I am currently using the latest 2.1s and the torch isn't affecting all blocks around it. The block that was the issue was the Ender IO Alloy Smelter. I had to move the torch to get it working. I was using the double compressed with all the options at the highest. I only move it over one spot and it started working on that block. They were all on the same layer. I also tried it twice to make sure.

o = block space,  x = alloy smelter, i = torch

Not working
oox
ooo
ioo

Working
oox
ooo
oio

**Comment by sci4me** [comment]
Someone should see if this is still a problem in 2.2s...
