### ISSUE TITLE
Torcherino reset settings when unload world

### ISSUE THREAD

**Issue by abdullamu** [sci4me/Torcherino#19]
everytime i load my game or travel through demintion the torch reset its setting so i have to visit all the areas and set them up again it .

**Comment by sci4me** [comment]
Which specific type of torch? I haven't had this problem myself...

**Comment by abdullamu** [comment]
its the torchorino with different type of setting always rest and i have to visit the area and set the speed and the area

**Comment by sci4me** [comment]
I don't understand, I mean... is it Torcherino, Inverted Torcherino, Compressed Torcherino, Inverted  Compressed Torcherino, Super Torcherino, or Inverted  Super Torcherino

**Comment by abdullamu** [comment]
i didnt know they exist but the normal one when i write in NEI i get only one with the name torcherino and no others

**Comment by sci4me** [comment]
Oh then you don't have them enabled. As for the bug, looking into it, but it shouldn't happen... you're the only person having this problem that I know of... weird.

**Comment by abdullamu** [comment]
does updating other mods affect that and rest it ?
like achievements for example

**Comment by Omnissia** [comment]
Same here, I've also been using regular torcherinos (cause was unaware of new ones) and they loose their settings if a chunk containing them was unloaded. Never had this problem before latest update
