### ISSUE TITLE
Dinnerbone?

### ISSUE THREAD

**Issue by UnRealDinnerbone** [sci4me/Torcherino#25]
For Some Reason When sci4me says UNREAL it comes out as dinnerbone 
CrashReport: http://pastebin.com/vXmQ21RM

**Comment by Mitchellbrine** [comment]
Can confirm!

**Comment by Mitchellbrine** [comment]
This is a serious problem

**Comment by Mitchellbrine** [comment]
Don't close this

**Comment by sci4me** [comment]
Locked due to spam.
