### ISSUE TITLE
Playing Hermitpack: my torcherino stopped working

### ISSUE THREAD

**Issue by Freedor7** [sci4me/Torcherino#30]
It was working just fine, then suddenly, I was unable to activate it. I can change the radius of effect just fine, but I'm shift+clicking away, and can't activate the 200%, 300%, etc.

I also have a creative world, and it seems to be working just fine in that one. I've restarting the the numerous times, even tried crafting a new torcherino, but nothing. I can set the radius, but not the effect.

Help?

**Comment by ssteward54** [comment]
Make sure you have nothing in your off hand or it doesn't work.

**Comment by Freedor7** [comment]
Wow. Now I feel like a complete idiot. I completely forgot about the off hand.

THANKS!
